app/api/urls.py
from django.urls import path, include
from api.views import LinkAPIView, CreateLinkAPIView, DecodeLinkAPIView


app_name = 'apiv1'


urlpatterns = [
    path('user-links/', LinkAPIView.as_view(), name='links_list'),
    path('create-link/', CreateLinkAPIView.as_view(), name='create_link'),
    path('decode-url/', DecodeLinkAPIView.as_view(), name='decode_url'),
]

app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from .yasg import urlpatterns as swagger_urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('links.urls')),
    path('api/v1/api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/v1/', include('api.urls')),
    path('users/', include('users.urls')),
]

urlpatterns += swagger_urls

app/links/urls.py
from django.urls import path
from .views import index_route


app_name = 'links'


urlpatterns = [
    path('', index_route, name='index'),
]

app/users/urls.py
from django.urls import path
from .views import login_user, logout_user, register_user, profile_user


app_name = 'users'

urlpatterns = [
    path('register/', register_user, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('profile/', profile_user, name='profile'),
]

app/api/models.py
from django.db import models

# Create your models here.

app/links/models.py
from django.db import models
from django.contrib.auth import get_user_model


class Links(models.Model):
    '''Модель для ссылок'''

    code = models.CharField(
        max_length=8, 
        unique=True, 
        db_index=True, 
        default='qwertyui'
    )
    old_url = models.URLField(max_length=1000)
    new_url = models.CharField(max_length=100, unique=True, db_index=True)
    user = models.ForeignKey(
        get_user_model(), 
        null=True, 
        blank=True,  
        on_delete=models.CASCADE, 
        related_name='links', 
        db_index=True
    )
    created_at = models.DateTimeField(auto_now_add=True)
    last_access = models.DateTimeField(max_length=500, auto_now=True)

    class Meta:
        verbose_name = 'Ссылку'
        verbose_name_plural = 'Ссылки'

    def __str__(self):
        return self.new_url

app/links/forms.py
from django import forms


class TinyUrlForm(forms.Form):
    '''Форма для главной страницы'''

    target_url = forms.URLField(
        required=True, 
        label='Shorter URLs', 
        help_text='Введите URL, который хотите сократить'
    )

app/users/forms.py
from django import forms
from django.contrib.auth import get_user_model


class LoginUserForm(forms.Form):
    '''Форма аутентификации'''

    username = forms.CharField(label='Логин', help_text='Введите ваш логин')
    password = forms.CharField(label='Пароль', help_text='Введите ваш пароль')


class RegisterUserForm(forms.ModelForm):
    '''Форма регистрации'''

    username = forms.CharField(label='Логин', help_text='Придумайте логин')
    password1 = forms.CharField(label='Пароль', help_text='Придумайте пароль', widget=forms.PasswordInput())
    password2 = forms.CharField(label='Повтор пароля', widget=forms.PasswordInput())

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']
        labels = {
            'email': 'E-mail',
            'first_name': 'Имя',
            'last_name': 'Фамилия'
        }

        help_texts = {
            'email': 'Введите вашу электронную почту'
        }


    def clean_password2(self) -> str:
        '''Метод сравнения password1 и password2'''
        
        cd = self.cleaned_data
        if cd['password1'] != cd['password2']:
            raise forms.ValidationError('Пароли не совпадают')
        return cd['password1']
    

    def clean_email(self) -> str:
        '''Метод для проверки - не занят ли email другим юзером'''
        
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError('Этот email занят')
        return email
    

app/api/views.py
from rest_framework import status
from rest_framework.response import Response
from rest_framework.exceptions import NotAuthenticated, NotFound
from rest_framework.views import APIView
from drf_yasg.utils import swagger_auto_schema
from drf_yasg import openapi
from links.models import Links
from .serializers import LinksSerializer
from links.utils import get_encode_url, get_decode_url


class LinkAPIView(APIView):
    '''API-route для возврата всех url-ов пользователя'''

    @swagger_auto_schema(responses={'200': LinksSerializer(many=True)})
    def get(self, request) -> Response:
        if request.user.is_authenticated:
            links = Links.objects.filter(user=request.user)
            return Response({'links': LinksSerializer(links, many=True).data})
        raise NotAuthenticated()


class CreateLinkAPIView(APIView):
    '''API-route для создания короткого url'''

    params = openapi.Parameter('url', openapi.IN_HEADER, description="Введите url который хотите сократить", type=openapi.TYPE_STRING)

    @swagger_auto_schema(manual_parameters=[params], responses={'200': LinksSerializer})
    def post(self, request) -> Response:
        target_url = request.headers['url']
        encode_url = get_encode_url(request.user, target_url)
        new_url = Links.objects.get(new_url=encode_url)            
        return Response(LinksSerializer(new_url).data, status=status.HTTP_201_CREATED)
    

class DecodeLinkAPIView(APIView):
    '''API-route для декодирования url'''

    params = openapi.Parameter('url', openapi.IN_HEADER, description="Введите url который нужно декодировать", type=openapi.TYPE_STRING)

    @swagger_auto_schema(manual_parameters=[params], responses={'200': LinksSerializer})
    def post(self, request) -> Response:
        target_url = request.headers['url']
        old_url = get_decode_url(target_url)  
        if old_url:     
            return Response(LinksSerializer(old_url).data, status=status.HTTP_200_OK)
        raise NotFound(code=status.HTTP_400_BAD_REQUEST, detail='Ссылка не найдена или вы ввели некорректоное значение')

app/links/views.py
from django.http import HttpResponse
from django.shortcuts import render
from .forms import TinyUrlForm
from .utils import get_encode_url


def index_route(request) -> HttpResponse:
    '''
        Роут для отображения главной страницы 
        с формой TinyUrlForm
    '''

    if request.method == 'POST':
        form = TinyUrlForm(request.POST)

        if form.is_valid():
            target_url = form.data['target_url']
            encode_url = get_encode_url(request.user, target_url)
            return render(request, 'links/index.html', {
                'form': form, 
                'encode_url': encode_url,
                'target_url': target_url,
            }) 
    else:
        form = TinyUrlForm()
        
    return render(request, 'links/index.html', {'form': form})

app/users/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .forms import LoginUserForm, RegisterUserForm


def register_user(request) -> HttpResponse:
    '''Роутер для регистрации юзеров'''
    
    if request.method == 'POST':
        form = RegisterUserForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password1'])
            user.save()
            return render(request, 'users/login.html')
    else:
        form = RegisterUserForm()
    return render(request, 'users/register.html', {'form': form})


def login_user(request) -> HttpResponseRedirect | HttpResponse:
    '''Роутер для аутентификации юзеров'''

    if request.method == 'POST':
        form = LoginUserForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(
                request, 
                username=cd['username'], 
                password=cd['password']
            )

            if user and user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('links:index'))
    else:
        form = LoginUserForm()
    
    return render(request, 'users/login.html', {'form': form})


def logout_user(request) -> HttpResponse:
    '''Роутер для логаута юзеров'''

    logout(request)
    return HttpResponseRedirect(reverse('users:login'))


@login_required
def profile_user(request) -> HttpResponse:
    '''Роутер для отображения профиля юзера'''

    links_list = request.user.links.order_by('-created_at')
    return render(request, 'users/profile.html', {
        'user': request.user,
        'links': links_list
    })

app/templates/base.html
<!DOCTYPE html>
<html lang='en'>
<head>
    <meta charset='UTF-8'>
    <meta name='viewport' content='width=device-width, initial-scale=1.0'>
    <script src='https://cdn.tailwindcss.com'></script>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% load static %}
    <link rel="stylesheet" href='{% static "css/styles.css" %}'' />
    <title>{% block title %}sURL{% endblock %}</title>
</head>
<body>
    <nav class='border-b border-gray-300'>
        <div class='max-w-6xl mx-auto px-6 xl:px-0 flex items-center justify-between'>
            <div class='menu-left flex items-center space-x-6'>
                <a href='/' class='py-4 text-lg text-purple-500 font-semibold'>Главная</a>
                <ul class='flex items-center space-x-4'>
                    <li><a href='{% url "schema-swagger-ui" %}'>API</a></li>
                </ul>
            </div>
            <div class='menu-right flex items-center space-x-4'>
                {% if user.is_authenticated %}
                    <a href="{% url 'users:profile' %}">
                        <svg xmlns='http://www.w3.org/2000/svg' fill='none' viewBox='0 0 24 24' stroke-width='1.5' stroke='currentColor' class='w-6 h-6'>
                            <path stroke-linecap='round' stroke-linejoin='round' d='M15.75 6a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0zM4.501 20.118a7.5 7.5 0 0114.998 0A17.933 17.933 0 0112 21.75c-2.676 0-5.216-.584-7.499-1.632z' />
                        </svg>                      
                    </a>
                    <a href="{% url 'users:logout' %}">Выйти</a>
                {% else %}
                    <a href="{% url 'users:register' %}">Регистрация</a>
                    <a href="{% url 'users:login' %}">Войти</a>
                {% endif %}
            </div>
        </div>
    </nav>
    <br>
    {% block content %}
    {% endblock %}
    <br>
    <br>
    <div class="footer">
        <footer class="bg-body-tertiary text-center text-lg-start">
            <!-- Copyright -->
            <div class="text-center p-3">
                © 2024 Copyright:
                <a class="text-body" href="/">sURL.com</a>
            </div>
            <!-- Copyright -->
        </footer>
    </div>
</body>
</html>

app/templates/links/index.html
{% extends 'base.html' %}


{% block content %}
<div class="container px-1">
    <div class="row justify-content-md-center">
        <div class="col-md-5">
            <p class="h2 row justify-content-md-center">sURL</p>
            <div class="m-4 p-4 border bg-light">
                <form method="post">
                    {% csrf_token %}
                    
                    <div class="form-group">
                        {{ form.target_url.label }} | (https://...)
                        <input type="url"  class="form-control"  name="{{ form.target_url.name }}" id="{{ form.target_url.name }}" placeholder="{{ form.target_url.help_text }}">
                        {% if encode_url %}
                            <br>
                            Результат: <a href="{{ target_url }}">{{ encode_url }}</a>
                        {% endif %}
                    </div>
                    <br>

                    <button type="submit" class="btn btn-primary">Сформировать ссылку</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

app/templates/users/login.html
{% extends 'base.html' %}
{% load users_tags %}

{% block title %}sURL | Вход{% endblock %}

{% block content %}
<div class="container px-1">
    <div class="row justify-content-md-center">
        <div class="col-md-5">
            <p class="h2 row justify-content-md-center">Вход</p>
            <div class="m-4 p-4 border bg-light">
                <form method="post">
                    {% csrf_token %}
                    
                    {% for i in form %}
                        <div class="form-group">
                            {{ i.label }}
                            <input type="{% get_input_type i.name %}"  class="form-control"  name="{{ i.name }}" id="{{ i.name }}" placeholder="{{ i.help_text }}">
                        </div>
                        <br>
                    {% endfor %}

                    <button type="submit" class="btn btn-primary">Войти</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

app/templates/users/profile.html
{% extends 'base.html' %}

{% block title %}sURL | Профиль{% endblock %}

{% block content %}
<div class="container px-1">
    <div class="row justify-content-md-center">
        <div class="col-md-15">
            <p class="h2 row justify-content-md-center">Профиль: {{ user.username }}</p>
            <p class="h4 row justify-content-md-center text-muted">Мои ссылки</p>
            <div class="m-4 p-4 border bg-light">
                {% if links %}
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Старый URL</th>
                            <th scope="col">Новый URL</th>
                            <th scope="col">Дата создания</th>
                        </tr>
                        </thead>
                        <tbody>
                            {% for link in links %}
                                <tr>
                                    <th scope="row">{{ forloop.counter }}</th>
                                    <td><a href="{{ link.old_url }}" title="{{ link.old_url }}" >{{ link.old_url|truncatechars:60 }}</a></td>
                                    <td><a href="{{ link.old_url }}">{{ link.new_url|truncatechars:40}}</a></td>
                                    <td>{{ link.created_at }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                    <p class="h4 row justify-content-md-center text-muted">У вас нет ни одной ссылки</p>
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock %}

app/templates/users/register.html
{% extends 'base.html' %}
{% load users_tags %}

{% block title %}sURL | Регистрация{% endblock %}

{% block content %}
<div class="container px-1">
    <div class="row justify-content-md-center">
        <div class="col-md-5">
            <p class="h2 row justify-content-md-center">Регистрация</p>
            <div class="m-4 p-4 border bg-light">
                <form method="post">
                    {% csrf_token %}

                    {% for i in form %}
                        <div class="form-group">
                            {{ i.label }}
                            <input type="{% get_input_type i.name %}"  class="form-control" name="{{ i.name }}" id="{{ i.name }}" placeholder="{{ i.help_text }}">
                        </div>
                        <br>
                    {% endfor %}

                    <button type="submit" class="btn btn-primary">Регистрация</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}